// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyprmevdtiueyzatugen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5cHJtZXZkdGl1ZXl6YXR1Z2VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MzA4MzUsImV4cCI6MjA2NjEwNjgzNX0.iqWARePfb-CFUqeL-9ILtclWviTNnG1HCq3UPv9zK2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);